### ISSUE TITLE
AUTH_USER_MODEL with DDD

### ISSUE THREAD

**Issue by youssef3wi** [jdiazromeral/django-ddd#8]
Hi, i'm new to django but i like the way you treat the app with the hexagonal architecture. I have an error with use the AbstractUser with a customer in the domain.
`django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'app_name.User' that has not been installed`

**Comment by jdiazromeral** [comment]
Hi, I will need more information about how you have configured your project. Can you share with me your settings?

**Comment by youssef3wi** [comment]
Of course it's a sample project.

‘DEBUG = True
ALLOWED_HOSTS = []
# Application definition
INSTALLED_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_ddd',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'visio_conf.infrastructure',
    'visio_conf.domain',
    'myapi.apps.MyapiConfig'
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'VisioConference.urls'
       

DATABASES = {
    'default': {
      
    }
}

AUTH_USER_MODEL = 'visio_conf.User'
´

**Comment by jdiazromeral** [comment]
On `INSTALLED_APPS`, you should only declare `visio_conf`, not each subfolder.

**Comment by youssef3wi** [comment]
even with the app_name in the INSTALLED_APPS i must create a models file with all classes in same file but the DDD not applicated here ```No module named 'visio_conf.models'```

**Comment by youssef3wi** [comment]
i forget the 3 famous configuration

CUSTOM_MODELS_MODULE = "infrastructure.models"
CUSTOM_MIGRATIONS_MODULE = "infrastructure.migrations"
CUSTOM_ADMIN_MODULE = "infrastructure.admin"
